### ISSUE TITLE
[help]: 英文好使，中文不好使

### ISSUE THREAD

**Issue by windily-cloud** [zcysxy/obsidian-pandoc-filters#1]
运行命令`pandoc --defaults ../Config/Pandoc/defaults/pdf.yaml .\pandoc测试.md`报错：

```bash
Error producing PDF.
! LaTeX Error: Unicode character 求 (U+6C42)
               not set up for use with LaTeX.
```

如果将所有内容改成英文就没事。

尝试手动设置字体：`pandoc --variable mainfont="SimSun" --defaults ../Config/Pandoc/defaults/pdf.yaml .\pandoc测试.md`，这个手动设置字体在不要模板的情况下是好使的。

尝试在`pdf.yaml`中设置中文字体：

```yaml
variables:
  latex_engine: xelatex
  mainfont="SimSun"
```
也是报相同的错误。这玩意儿我也不知道怎么debug，大佬有啥好的建议没？

感谢大佬的分享，这玩意儿好棒。🤗🤗🤗
